name: Check Markdown links
on:
  pull_request:
    paths:
      - '**.md'
permissions:
  contents: read

jobs:
  lint-md:
    runs-on:
      - self-hosted
      - 1ES.Pool=MC-Runner-1ES-Linux
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npx remark --use validate-links --frail . .github
